BEGIN TRANSACTION;

CREATE TABLE IF NOT EXISTS "transaction" (
  "id" SERIAL PRIMARY KEY,
  "from_id" INTEGER,
  "to_id" INTEGER,
  "amount" DECIMAL(15,2) NOT NULL,
  "created_at" TIMESTAMP DEFAULT (NOW()),
  "updated_at" TIMESTAMP DEFAULT (NOW())
);

ALTER TABLE "transaction"
    ADD FOREIGN KEY ("from_id") REFERENCES "account" ("id")  ON DELETE CASCADE ON UPDATE CASCADE,
    ADD FOREIGN KEY ("to_id") REFERENCES "account" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "account"
   ALTER COLUMN "balance" TYPE DECIMAL(15,2) USING balance::DECIMAL(15,2);

COMMIT;
